spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}


ingestion:
  poll-rate-ms: 1000    # poll every 1 second

server:
  port: 8080

logging:
  level:
    root: INFO
    com.trading.platform.core.ingestion: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

zerodha:
  api-key: ${ZERODHA_API_KEY:}
  access-token: ${ZERODHA_ACCESS_TOKEN:}

trading:
  mode: paper
